/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAiChatbotAutomationRouteImport } from './routes/services.ai-chatbot-automation'
import { Route as ServicesAiSeoRouteImport } from './routes/services.ai-seo'
import { Route as ServicesContentWritingRouteImport } from './routes/services.content-writing'
import { Route as ServicesGoogleMetaAdsRouteImport } from './routes/services.google-meta-ads'
import { Route as ServicesSocialMediaManagementRouteImport } from './routes/services.social-media-management'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiChatbotAutomationRoute =
  ServicesAiChatbotAutomationRouteImport.update({
    id: '/ai-chatbot-automation',
    path: '/ai-chatbot-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiSeoRoute = ServicesAiSeoRouteImport.update({
  id: '/ai-seo',
  path: '/ai-seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesContentWritingRoute = ServicesContentWritingRouteImport.update({
  id: '/content-writing',
  path: '/content-writing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGoogleMetaAdsRoute = ServicesGoogleMetaAdsRouteImport.update({
  id: '/google-meta-ads',
  path: '/google-meta-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSocialMediaManagementRoute =
  ServicesSocialMediaManagementRouteImport.update({
    id: '/social-media-management',
    path: '/social-media-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/website-development',
    path: '/website-development',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-chatbot-automation': typeof ServicesAiChatbotAutomationRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-writing': typeof ServicesContentWritingRoute
  '/services/google-meta-ads': typeof ServicesGoogleMetaAdsRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-chatbot-automation': typeof ServicesAiChatbotAutomationRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-writing': typeof ServicesContentWritingRoute
  '/services/google-meta-ads': typeof ServicesGoogleMetaAdsRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-chatbot-automation': typeof ServicesAiChatbotAutomationRoute
  '/services/ai-seo': typeof ServicesAiSeoRoute
  '/services/content-writing': typeof ServicesContentWritingRoute
  '/services/google-meta-ads': typeof ServicesGoogleMetaAdsRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ai-chatbot-automation'
    | '/services/ai-seo'
    | '/services/content-writing'
    | '/services/google-meta-ads'
    | '/services/social-media-management'
    | '/services/website-development'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ai-chatbot-automation'
    | '/services/ai-seo'
    | '/services/content-writing'
    | '/services/google-meta-ads'
    | '/services/social-media-management'
    | '/services/website-development'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ai-chatbot-automation'
    | '/services/ai-seo'
    | '/services/content-writing'
    | '/services/google-meta-ads'
    | '/services/social-media-management'
    | '/services/website-development'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-chatbot-automation': {
      id: '/services/ai-chatbot-automation'
      path: '/ai-chatbot-automation'
      fullPath: '/services/ai-chatbot-automation'
      preLoaderRoute: typeof ServicesAiChatbotAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-seo': {
      id: '/services/ai-seo'
      path: '/ai-seo'
      fullPath: '/services/ai-seo'
      preLoaderRoute: typeof ServicesAiSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content-writing': {
      id: '/services/content-writing'
      path: '/content-writing'
      fullPath: '/services/content-writing'
      preLoaderRoute: typeof ServicesContentWritingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/google-meta-ads': {
      id: '/services/google-meta-ads'
      path: '/google-meta-ads'
      fullPath: '/services/google-meta-ads'
      preLoaderRoute: typeof ServicesGoogleMetaAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media-management': {
      id: '/services/social-media-management'
      path: '/social-media-management'
      fullPath: '/services/social-media-management'
      preLoaderRoute: typeof ServicesSocialMediaManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesAiChatbotAutomationRoute: typeof ServicesAiChatbotAutomationRoute
  ServicesAiSeoRoute: typeof ServicesAiSeoRoute
  ServicesContentWritingRoute: typeof ServicesContentWritingRoute
  ServicesGoogleMetaAdsRoute: typeof ServicesGoogleMetaAdsRoute
  ServicesSocialMediaManagementRoute: typeof ServicesSocialMediaManagementRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiChatbotAutomationRoute: ServicesAiChatbotAutomationRoute,
  ServicesAiSeoRoute: ServicesAiSeoRoute,
  ServicesContentWritingRoute: ServicesContentWritingRoute,
  ServicesGoogleMetaAdsRoute: ServicesGoogleMetaAdsRoute,
  ServicesSocialMediaManagementRoute: ServicesSocialMediaManagementRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
